language: python
python:
- '3.6'
before_install:
- sudo apt-get install gfortran openmpi-bin libopenmpi-dev
install:
- pip install git+https://github.com/pyccel/fffi#egg=fffi
- pip install coverage codacy-coverage
- pip install scipy==1.2.1  # bugfix for chaospy scipy.misc.comb
- pip install --upgrade pytest
- git clone $UQP
- cd uqp && make && cd ..
- export UQP_HOME=`pwd`/uqp
- ln -s $UQP_HOME/libuqp.so tests/backend_uqp/libuqp.so
- pip install -e .
script:
- coverage run setup.py test
- coverage xml
- python-codacy-coverage
